namespace: vaultwarden
createNamespace: true

replicaCount: 1

image:
  repository: vaultwarden/server
  tag: latest@sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
  pullPolicy: IfNotPresent

deploymentAnnotations:
  keel.sh/policy: all

domain: https://vaultwarden.home.tom-mendy.com

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: vaultwarden.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

storage:
  pvName: vaultwarden-data-pv
  pvcName: vaultwarden-data-pvc
  size: 10Gi
  nfsServer: 192.168.1.1
  nfsPath: /volume1/vaultwarden
