namespace: vaultwarden
createNamespace: true

replicaCount: 1

image:
  repository: vaultwarden/server
  tag: 1.37.2-alpine@sha256:d16a304c2476fd787634ddde2c00be8fdfa1a72539438c626ece3686b5b88ab4
  pullPolicy: IfNotPresent

domain: https://vaultwarden.home.tom-mendy.com

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: vaultwarden.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

storage:
  pvName: vaultwarden-data-pv
  pvcName: vaultwarden-data-pvc
  size: 10Gi
  nfsServer: 10.0.0.11
  nfsPath: /volume1/vaultwarden
