apiVersion: v1
kind: Namespace
metadata:
  name: blocky
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  namespace: blocky
  annotations:
    keel.sh/policy: minor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      labels:
        app: blocky
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "4000"
    spec:
      containers:
      - name: blocky
        image: spx01/blocky:latest
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 4000
          name: http
        volumeMounts:
        - name: config
          mountPath: /app/config.yml
          subPath: config.yml
      volumes:
      - name: config
        configMap:
          name: blocky-config
---
apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.21
spec:
  type: LoadBalancer
  selector:
    app: blocky
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000