apiVersion: v1
kind: Namespace
metadata:
  name: blocky
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  namespace: blocky
  annotations:
    keel.sh/policy: minor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      labels:
        app: blocky
    spec:
      containers:
      - name: blocky
        image: spx01/blocky:v0.26
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 4000
          name: http
        volumeMounts:
        - name: config
          mountPath: /app/config.yml
          subPath: config.yml
      volumes:
      - name: config
        configMap:
          name: blocky-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: blocky
data:
  config.yml: |
    upstream:
      default:
        - 1.1.1.1
        - 8.8.8.8
        - 192.168.1.254
    customDNS:
      mapping:
        keel.tom-mendy.local: 192.168.1.20
        trilium.tom-mendy.local: 192.168.1.20
        blocky.tom-mendy.local: 192.168.1.20
        ollama.tom-mendy.local: 192.168.1.20
        openwebui.tom-mendy.local: 192.168.1.20
    port: 53
    httpPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.21
spec:
  type: LoadBalancer
  selector:
    app: blocky
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
  - name: http
    protocol: TCP
    port: 4000
    targetPort: 4000