upstreams:
  groups:
    default:
      - 9.9.9.9
      - 2620:fe::fe
      - 1.1.1.2
      - 2606:4700:4700::1112
      - 1.1.1.1
      - 2606:4700:4700::1111
      - 8.8.8.8
      - 10.0.0.1
      - 2001:861:5285:37e3:ca9e:43ff:fedf:9926
      - 192.168.1.254
customDNS:
  mapping:
    prowlarr.home.tom-mendy.com: 10.0.0.60
    sonarr.home.tom-mendy.com: 10.0.0.60
    radarr.home.tom-mendy.com: 10.0.0.60
    bazarr.home.tom-mendy.com: 10.0.0.60
    qbittorrent.home.tom-mendy.com: 10.0.0.60
    nzbget.home.tom-mendy.com: 10.0.0.60
    autobrr.home.tom-mendy.com: 10.0.0.60
    trilium.home.tom-mendy.com: 10.0.0.60
    blocky.home.tom-mendy.com: 10.0.0.60
    ollama.home.tom-mendy.com: 10.0.0.60
    openwebui.home.tom-mendy.com: 10.0.0.60
    searxng.home.tom-mendy.com: 10.0.0.60
    stirling-pdf.home.tom-mendy.com: 10.0.0.60
    navidrome.home.tom-mendy.com: 10.0.0.60
    vaultwarden.home.tom-mendy.com: 10.0.0.60
    homepage.home.tom-mendy.com: 10.0.0.60
    prometheus.home.tom-mendy.com: 10.0.0.60
    forgejo.tom-mendy.com: 10.0.0.60
    forgejo.home.tom-mendy.com: 10.0.0.60
    grafana.home.tom-mendy.com: 10.0.0.60
    atuin.home.tom-mendy.com: 10.0.0.60
    infisical.home.tom-mendy.com: 10.0.0.60
    authentik.home.tom-mendy.com: 10.0.0.60
    flux.home.tom-mendy.com: 10.0.0.60
    coder.home.tom-mendy.com: 10.0.0.60
blocking:
  denylists:
    strict:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt
  clientGroupsBlock:
    default:
      - strict
prometheus:
  enable: true
  path: /metrics
ports:
  dns: 53
  http: 4000
