upstream:
  default:
    - 9.9.9.9
    - 1.1.1.2
    - 1.1.1.1
    - 8.8.8.8
    - 192.168.1.254
customDNS:
  mapping:
    keel.home.tom-mendy.com: 192.168.1.20
    trilium.home.tom-mendy.com: 192.168.1.20
    blocky.home.tom-mendy.com: 192.168.1.20
    ollama.home.tom-mendy.com: 192.168.1.20
    openwebui.home.tom-mendy.com: 192.168.1.20
    navidrome.home.tom-mendy.com: 192.168.1.20
    vaultwarden.home.tom-mendy.com: 192.168.1.20
    homepage.home.tom-mendy.com: 192.168.1.20
    prometheus.home.tom-mendy.com: 192.168.1.20
port: 53
httpPort: 4000
