namespace: blocky
createNamespace: true

replicaCount: 1

image:
  repository: spx01/blocky
  tag: v0.30.0@sha256:d9f15eddffedded40797406349012cbd5966ef99c286b13321e7a76efddb9bdc
  pullPolicy: IfNotPresent

deploymentAnnotations:
  keel.sh/policy: minor

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "4000"

service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.61
  dnsPort: 53
  httpPort: 4000
