{{- $app := .Values.apps.bazarr }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default .Values.configStorage.defaultSize $app.configSize }}
  storageClassName: {{ .Values.configStorage.className }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: {{ .Values.namespace }}
  annotations:
    keel.sh/policy: all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
        - name: bazarr
          image: {{ $app.image | quote }}
          env:
            - name: PUID
              value: {{ .Values.securityContext.puid | quote }}
            - name: PGID
              value: {{ .Values.securityContext.pgid | quote }}
            - name: TZ
              value: {{ .Values.timezone | quote }}
          ports:
            - containerPort: {{ $app.port }}
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if $app.mounts.movies }}
            - name: movies
              mountPath: /data/media/movies
            {{- end }}
            {{- if $app.mounts.series }}
            - name: series
              mountPath: /data/media/tv
            {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
        {{- if $app.mounts.movies }}
        - name: movies
          persistentVolumeClaim:
            claimName: media-movies-pvc
        {{- end }}
        {{- if $app.mounts.series }}
        - name: series
          persistentVolumeClaim:
            claimName: media-series-pvc
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: bazarr
  ports:
    - name: http
      port: {{ $app.port }}
      targetPort: {{ $app.port }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-ingress
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ $app.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bazarr
                port:
                  number: {{ $app.port }}
{{- end }}
