{{- if .Values.infisicalSecret.enabled }}
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: {{ .Values.infisicalSecret.connectionName }}
  namespace: {{ .Values.namespace }}
spec:
  address: {{ .Values.infisicalSecret.address | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infisicalSecret.identitySecretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  identityId: {{ .Values.infisicalSecret.identityID | quote }}
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: {{ .Values.infisicalSecret.authName }}
  namespace: {{ .Values.namespace }}
spec:
  method: kubernetes
  infisicalConnectionRef:
    name: {{ .Values.infisicalSecret.connectionName }}
    namespace: {{ .Values.namespace }}
  kubernetes:
    identityIdRef:
      name: {{ .Values.infisicalSecret.identitySecretName }}
      namespace: {{ .Values.namespace }}
      key: identityId
    serviceAccountRef:
      name: {{ .Values.infisicalSecret.serviceAccountName }}
      namespace: {{ .Values.namespace }}
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: {{ .Values.infisicalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  infisicalAuthRef:
    name: {{ .Values.infisicalSecret.authName }}
    namespace: {{ .Values.namespace }}
  sources:
    - projectId: {{ .Values.infisicalSecret.projectId | quote }}
      environmentSlug: {{ .Values.infisicalSecret.envSlug | quote }}
      secretPath: {{ .Values.infisicalSecret.secretsPath | quote }}
      recursive: false
  targets:
    - name: {{ .Values.vpn.secretName }}
      namespace: {{ .Values.namespace }}
      kind: Secret
      creationPolicy: Orphan
      secretType: Opaque
      template:
        engineVersion: v1
        data:
          WIREGUARD_PRIVATE_KEY: "{{`{{ .WIREGUARD_PRIVATE_KEY.Value }}`}}"
    - name: {{ .Values.nymVpn.secretName }}
      namespace: {{ .Values.namespace }}
      kind: Secret
      creationPolicy: Orphan
      secretType: Opaque
      template:
        engineVersion: v1
        data:
          NYM_ACCESS_CODE: "{{`{{ .NYM_ACCESS_CODE.Value }}`}}"
  syncOptions:
    refreshInterval: 1m
    instantUpdates: false
{{- end }}
