{{- if and .Values.vpn.enabled .Values.vpn.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vpn.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- if eq (lower .Values.vpn.type) "wireguard" }}
  WIREGUARD_PRIVATE_KEY: {{ .Values.vpn.credentials.wireguardPrivateKey | quote }}
  {{- else }}
  OPENVPN_USER: {{ .Values.vpn.credentials.openvpnUser | quote }}
  OPENVPN_PASSWORD: {{ .Values.vpn.credentials.openvpnPassword | quote }}
  {{- end }}
{{- end }}
