namespace: searxng
createNamespace: true

replicaCount: 1

image:
  repository: searxng/searxng
  tag: ""
  digest: sha256:a7f9188cc7fa8b6b037e0d85709c0dced8f05d0eba84145eb7fe7027a4c00850
  pullPolicy: IfNotPresent

deploymentAnnotations:
  keel.sh/policy: all

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: searxng.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

env:
  instanceName: SearXNG
  baseUrl: https://searxng.home.tom-mendy.com/
  autocomplete: duckduckgo

secret:
  name: searxng-secret
  create: false
  serverSecretKey: ""

vpn:
  enabled: true
  createSecret: false
  secretName: searxng-vpn-secret
  serviceProvider: protonvpn
  type: wireguard
  firewall: "on"
  serverCountries: "France"
  credentials:
    wireguardPrivateKey: ""
    openvpnUser: "your_openvpn_username"
    openvpnPassword: "your_openvpn_password"

infisicalSecret:
  enabled: true
  name: searxng-secrets
  serviceAccountName: searxng-infisical-sync
  connectionName: searxng-infisical
  authName: searxng-infisical
  identitySecretName: searxng-infisical-identity
  address: https://infisical.home.tom-mendy.com
  identityID: "c4027cca-f8d6-4d36-a73c-2dc61baf2016"
  projectId: "758123bc-7eaa-4256-98a2-bb7438a783b8"
  envSlug: prod
  secretsPath: /searxng
