namespace: searxng
createNamespace: true

replicaCount: 1

image:
  repository: searxng/searxng
  tag: ""
  digest: sha256:11a9b34cdc0b1ec2b991470a2762ecb5a1a531898289fb51dcd015260450729e
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: searxng.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

env:
  instanceName: SearXNG
  baseUrl: https://searxng.home.tom-mendy.com/
  autocomplete: duckduckgo

secret:
  name: searxng-secret
  create: false
  serverSecretKey: ""

nymVpn:
  image: forgejo.tom-mendy.com/tom-mendy/nymvpn-sidecar:2026.11.3-3@sha256:0728350cf1d4012b09a8674f58d6ad4290da11cf8db115ceb051fe91dfba25d6
  pullPolicy: IfNotPresent
  secretName: searxng-nymvpn-credentials
  entryCountry: FR
  exitCountry: CH
  podCidr: 10.233.64.0/18
  stateStorage:
    className: nfs-k8s
    size: 1Gi

infisicalSecret:
  enabled: true
  name: searxng-secrets
  serviceAccountName: searxng-infisical-sync
  connectionName: searxng-infisical
  authName: searxng-infisical
  identitySecretName: searxng-infisical-identity
  address: https://infisical.home.tom-mendy.com
  identityID: "c4027cca-f8d6-4d36-a73c-2dc61baf2016"
  projectId: "758123bc-7eaa-4256-98a2-bb7438a783b8"
  envSlug: prod
  secretsPath: /searxng
