{{- if .Values.infisicalSecret.enabled }}
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalConnection
metadata:
  name: {{ .Values.infisicalSecret.connectionName }}
  namespace: {{ .Values.namespace }}
spec:
  address: {{ .Values.infisicalSecret.address | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infisicalSecret.identitySecretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  identityId: {{ .Values.infisicalSecret.identityID | quote }}
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: {{ .Values.infisicalSecret.authName }}
  namespace: {{ .Values.namespace }}
spec:
  method: kubernetes
  infisicalConnectionRef:
    name: {{ .Values.infisicalSecret.connectionName }}
    namespace: {{ .Values.namespace }}
  kubernetes:
    identityIdRef:
      name: {{ .Values.infisicalSecret.identitySecretName }}
      namespace: {{ .Values.namespace }}
      key: identityId
    serviceAccountRef:
      name: {{ .Values.infisicalSecret.serviceAccountName }}
      namespace: {{ .Values.namespace }}
---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: {{ .Values.infisicalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  infisicalAuthRef:
    name: {{ .Values.infisicalSecret.authName }}
    namespace: {{ .Values.namespace }}
  sources:
    - projectId: {{ .Values.infisicalSecret.projectId | quote }}
      environmentSlug: {{ .Values.infisicalSecret.envSlug | quote }}
      secretPath: {{ .Values.infisicalSecret.secretsPath | quote }}
      recursive: false
  targets:
    - name: {{ .Values.registryAuth.secretName }}
      namespace: {{ .Values.namespace }}
      kind: Secret
      creationPolicy: Orphan
      secretType: kubernetes.io/dockerconfigjson
      template:
        engineVersion: v1
        data:
          .dockerconfigjson: '{{`{{ printf "{\"auths\":{\"forgejo.home.tom-mendy.com\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .REGISTRY_USERNAME .REGISTRY_PASSWORD (printf "%s:%s" .REGISTRY_USERNAME .REGISTRY_PASSWORD | b64enc) }}`}}'
    - name: {{ .Values.env.secretName }}
      namespace: {{ .Values.namespace }}
      kind: Secret
      creationPolicy: Orphan
      secretType: Opaque
      template:
        engineVersion: v1
        data:
          ENDFIELD_CRED: "{{`{{ .ENDFIELD_CRED }}`}}"
          ENDFIELD_SK_GAME_ROLE: "{{`{{ .ENDFIELD_SK_GAME_ROLE }}`}}"
          ENDFIELD_PLATFORM: "{{`{{ .ENDFIELD_PLATFORM }}`}}"
          ENDFIELD_VNAME: "{{`{{ .ENDFIELD_VNAME }}`}}"
          ENDFIELD_ACCOUNT_NAME: "{{`{{ .ENDFIELD_ACCOUNT_NAME }}`}}"
          ENABLE_DISCORD_NOTIFY: "{{`{{ .ENABLE_DISCORD_NOTIFY }}`}}"
          DISCORD_WEBHOOK_URL: "{{`{{ .DISCORD_WEBHOOK_URL }}`}}"
          DISCORD_USER_ID: "{{`{{ .DISCORD_USER_ID }}`}}"
  syncOptions:
    refreshInterval: 1m
    instantUpdates: false
{{- end }}
