{{- if .Values.runOnceJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: endfield-manual-{{ .Release.Revision }}
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: {{ .Values.runOnceJob.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.runOnceJob.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app: endfield
        job-type: manual
    spec:
      restartPolicy: OnFailure
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: endfield
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.env.secretName }}
          securityContext:
{{ toYaml .Values.securityContext | nindent 12 }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
{{- end }}
