{{- if .Values.env.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ENDFIELD_CRED: {{ .Values.env.values.ENDFIELD_CRED | quote }}
  ENDFIELD_SK_GAME_ROLE: {{ .Values.env.values.ENDFIELD_SK_GAME_ROLE | quote }}
  ENDFIELD_PLATFORM: {{ .Values.env.values.ENDFIELD_PLATFORM | quote }}
  ENDFIELD_VNAME: {{ .Values.env.values.ENDFIELD_VNAME | quote }}
  ENDFIELD_ACCOUNT_NAME: {{ .Values.env.values.ENDFIELD_ACCOUNT_NAME | quote }}
  ENABLE_DISCORD_NOTIFY: {{ .Values.env.values.ENABLE_DISCORD_NOTIFY | quote }}
  DISCORD_WEBHOOK_URL: {{ .Values.env.values.DISCORD_WEBHOOK_URL | quote }}
  DISCORD_USER_ID: {{ .Values.env.values.DISCORD_USER_ID | quote }}
{{- end }}
