namespace: authentik

infisicalSecret:
  enabled: false
  name: authentik-secrets
  hostAPI: https://infisical.home.tom-mendy.com/api
  identityID: ""
  projectSlug: homelab
  envSlug: prod
  secretsPath: /authentik

