apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    log:
      level: {{ .Values.runner.logLevel | quote }}

    runner:
      file: /data/.runner
      capacity: {{ .Values.runner.capacity }}
      timeout: {{ .Values.runner.timeout | quote }}
      envs:
        DOCKER_HOST: {{ .Values.docker.jobHost | quote }}
      labels:
{{- range .Values.runner.labels }}
        - {{ . | quote }}
{{- end }}

    cache:
      enabled: true
      dir: /data/cache

    container:
      network: bridge
      docker_host: {{ .Values.docker.host | quote }}
      options: {{ .Values.docker.containerOptions | quote }}

    host:
      workdir_parent: /data/work
