namespace: arc-runners

secret:
  name: arc-github-auth

infisicalSecret:
  enabled: true
  name: arc-github-auth
  serviceAccountName: github-runners-infisical-sync
  connectionName: github-runners-infisical
  authName: github-runners-infisical
  identitySecretName: github-runners-infisical-identity
  address: https://infisical.home.tom-mendy.com
  identityID: "7b887000-ae48-4603-8ed2-89a5bd6f1f5e"
  projectId: "758123bc-7eaa-4256-98a2-bb7438a783b8"
  envSlug: prod
  secretsPath: /github-runners
