githubConfigUrl: "https://github.com/MrAmarok/sumfeet"
githubConfigSecret: arc-github-auth-sumfeet

runnerScaleSetName: "arc-runner-set-sumfleet-tom"

scaleSetLabels:
  - self-hosted

maxRunners: 20
minRunners: 0

containerMode:
  type: "dind"

controllerServiceAccount:
  namespace: arc-systems
  name: arc-gha-rs-controller

template:
  spec:
    containers:
      - name: runner
        image: harbor.home.tom-mendy.com/runners/sumfeet-actions-runner@sha256:d5f0e5422671a8c1d61eb422970c67cf0618e53fb1c79780dd87de865d682a12
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "4"
            memory: "4Gi"
