githubConfigUrl: "https://github.com/MrAmarok/sumfeet"
githubConfigSecret: arc-github-auth-sumfeet

runnerScaleSetName: "arc-runner-set-sumfleet-tom"

scaleSetLabels:
  - self-hosted

maxRunners: 20
minRunners: 0

containerMode:
  type: "dind"

controllerServiceAccount:
  namespace: arc-systems
  name: arc-gha-rs-controller

template:
  spec:
    containers:
      - name: runner
        image: harbor.home.tom-mendy.com/runners/sumfeet-actions-runner@sha256:90e45f1551f4c7a617b1838c97f70695e2c8bc05759a823ec03a824654760b62
        command: ["/home/runner/run.sh"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "4"
            memory: "4Gi"
