version: 1
metadata:
  name: Homelab OIDC clients
entries:
  - model: authentik_core.group
    id: homelab-admins
    identifiers:
      name: homelab-admins
    attrs:
      is_superuser: true
  - model: authentik_core.group
    id: homelab-guests
    identifiers:
      name: homelab-guests
  - model: authentik_core.group
    id: forgejo-users
    identifiers:
      name: forgejo-users
  - model: authentik_core.group
    id: grafana-users
    identifiers:
      name: grafana-users
  - model: authentik_core.group
    id: flux-viewers
    identifiers:
      name: flux-viewers
  - model: authentik_core.group
    id: coder-users
    identifiers:
      name: coder-users
  - model: authentik_core.group
    id: matrix-users
    identifiers:
      name: matrix-users

  - model: authentik_core.group
    id: openwebui-users
    identifiers:
      name: openwebui-users

  - model: authentik_core.group
    id: media-users
    identifiers:
      name: media-users

  - model: authentik_core.group
    id: radarr-users
    identifiers:
      name: radarr-users
  - model: authentik_core.group
    id: sonarr-users
    identifiers:
      name: sonarr-users
  - model: authentik_core.group
    id: qbittorrent-users
    identifiers:
      name: qbittorrent-users

  - model: authentik_providers_proxy.proxyprovider
    id: hindsight-provider
    identifiers:
      name: Hindsight
    attrs:
      authentication_flow: !Find
        - authentik_flows.flow
        - [slug, default-authentication-flow]
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      external_host: https://hindsight.home.tom-mendy.com
      mode: forward_single
  - model: authentik_core.application
    id: hindsight-application
    identifiers:
      slug: hindsight
    attrs:
      name: Hindsight
      provider: !KeyOf hindsight-provider
      meta_launch_url: https://hindsight.home.tom-mendy.com/
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf hindsight-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true

  - model: authentik_providers_proxy.proxyprovider
    id: radarr-provider
    identifiers:
      name: Radarr
    attrs:
      authentication_flow: !Find
        - authentik_flows.flow
        - [slug, default-authentication-flow]
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      external_host: https://radarr.home.tom-mendy.com
      mode: forward_single
  - model: authentik_core.application
    id: radarr-application
    identifiers:
      slug: radarr
    attrs:
      name: Radarr
      provider: !KeyOf radarr-provider
      meta_launch_url: https://radarr.home.tom-mendy.com/
      meta_icon: https://raw.githubusercontent.com/Radarr/Radarr/develop/Logo/64.png
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf radarr-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf radarr-application
      group: !KeyOf radarr-users
      order: 1
    attrs:
      enabled: true

  - model: authentik_providers_proxy.proxyprovider
    id: sonarr-provider
    identifiers:
      name: Sonarr
    attrs:
      authentication_flow: !Find
        - authentik_flows.flow
        - [slug, default-authentication-flow]
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      external_host: https://sonarr.home.tom-mendy.com
      mode: forward_single
  - model: authentik_core.application
    id: sonarr-application
    identifiers:
      slug: sonarr
    attrs:
      name: Sonarr
      provider: !KeyOf sonarr-provider
      meta_launch_url: https://sonarr.home.tom-mendy.com/
      meta_icon: https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/64.png
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf sonarr-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf sonarr-application
      group: !KeyOf sonarr-users
      order: 1
    attrs:
      enabled: true
  - model: authentik_providers_proxy.proxyprovider
    id: qbittorrent-provider
    identifiers:
      name: qBittorrent
    attrs:
      authentication_flow: !Find
        - authentik_flows.flow
        - [slug, default-authentication-flow]
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      external_host: https://qbittorrent.home.tom-mendy.com
      mode: forward_single
  - model: authentik_core.application
    id: qbittorrent-application
    identifiers:
      slug: qbittorrent
    attrs:
      name: qBittorrent
      provider: !KeyOf qbittorrent-provider
      meta_launch_url: https://qbittorrent.home.tom-mendy.com/
      meta_icon: https://raw.githubusercontent.com/qbittorrent/qBittorrent/master/dist/logo/qbittorrent.png
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf qbittorrent-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf qbittorrent-application
      group: !KeyOf qbittorrent-users
      order: 1
    attrs:
      enabled: true
  - model: authentik_outposts.outpost
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      providers:
        - !KeyOf radarr-provider
        - !KeyOf sonarr-provider
        - !KeyOf hindsight-provider
        - !KeyOf qbittorrent-provider

  - model: authentik_providers_oauth2.scopemapping
    id: openwebui-roles-scope
    identifiers:
      name: Open WebUI roles
    attrs:
      name: Open WebUI roles
      scope_name: roles
      expression: |
        roles = []
        if ak_is_group_member(request.user, name="homelab-admins"):
          roles.extend(["openwebui-user", "openwebui-admin"])
        elif ak_is_group_member(request.user, name="openwebui-users"):
          roles.append("openwebui-user")
        return {"roles": roles}

  - model: authentik_providers_oauth2.oauth2provider
    id: openwebui-provider
    identifiers:
      name: Open WebUI
    attrs:
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      client_type: confidential
      client_id: openwebui
      client_secret: !Env [OPENWEBUI_OIDC_CLIENT_SECRET, null]
      issuer_mode: per_provider
      grant_types:
        - authorization_code
        - refresh_token
      redirect_uris:
        - matching_mode: strict
          url: https://openwebui.home.tom-mendy.com/oauth/oidc/callback
          redirect_uri_type: authorization
      property_mappings:
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-openid]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-email]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-profile]
        - !KeyOf openwebui-roles-scope
      signing_key: !Find
        - authentik_crypto.certificatekeypair
        - [name, authentik Self-signed Certificate]
  - model: authentik_core.application
    id: openwebui-application
    identifiers:
      slug: openwebui
    attrs:
      name: Open WebUI
      provider: !KeyOf openwebui-provider
      meta_launch_url: https://openwebui.home.tom-mendy.com/
      meta_icon: https://openwebui.home.tom-mendy.com/static/favicon.png
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf openwebui-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf openwebui-application
      group: !KeyOf openwebui-users
      order: 1
    attrs:
      enabled: true

  - model: authentik_providers_oauth2.oauth2provider
    id: forgejo-provider
    identifiers:
      name: forgejo
    attrs:
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      client_type: confidential
      client_id: forgejo
      client_secret: !Env [FORGEJO_OIDC_CLIENT_SECRET, null]
      issuer_mode: per_provider
      grant_types:
        - authorization_code
        - refresh_token
      redirect_uris:
        - matching_mode: strict
          url: https://forgejo.tom-mendy.com/user/oauth2/authentik/callback
          redirect_uri_type: authorization
      property_mappings:
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-openid]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-email]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-profile]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-offline_access]
      signing_key: !Find
        - authentik_crypto.certificatekeypair
        - [name, authentik Self-signed Certificate]
  - model: authentik_core.application
    id: forgejo-application
    identifiers:
      slug: forgejo
    attrs:
      name: Forgejo
      provider: !KeyOf forgejo-provider
      meta_launch_url: https://forgejo.tom-mendy.com/user/oauth2/authentik
      meta_icon: https://forgejo.tom-mendy.com/assets/img/logo.svg
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf forgejo-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf forgejo-application
      group: !KeyOf forgejo-users
      order: 1
    attrs:
      enabled: true

  - model: authentik_providers_oauth2.oauth2provider
    id: grafana-provider
    identifiers:
      name: Grafana
    attrs:
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      client_type: confidential
      client_id: grafana
      client_secret: !Env [GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET, null]
      issuer_mode: per_provider
      grant_types:
        - authorization_code
        - refresh_token
      redirect_uris:
        - matching_mode: strict
          url: https://grafana.home.tom-mendy.com/login/generic_oauth
          redirect_uri_type: authorization
      property_mappings:
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-openid]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-email]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-profile]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-offline_access]
      signing_key: !Find
        - authentik_crypto.certificatekeypair
        - [name, authentik Self-signed Certificate]
  - model: authentik_core.application
    id: grafana-application
    identifiers:
      slug: grafana
    attrs:
      name: Grafana
      provider: !KeyOf grafana-provider
      meta_launch_url: https://grafana.home.tom-mendy.com/
      meta_icon: https://grafana.home.tom-mendy.com/public/img/grafana_icon.svg
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf grafana-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf grafana-application
      group: !KeyOf grafana-users
      order: 1
    attrs:
      enabled: true

  - model: authentik_providers_oauth2.oauth2provider
    id: flux-provider
    identifiers:
      name: Flux
    attrs:
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      client_type: confidential
      client_id: flux-web
      client_secret: !Env [FLUX_WEB_CLIENT_SECRET, null]
      issuer_mode: per_provider
      grant_types:
        - authorization_code
        - refresh_token
      redirect_uris:
        - matching_mode: strict
          url: https://flux.home.tom-mendy.com/oauth2/callback
          redirect_uri_type: authorization
      property_mappings:
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-openid]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-email]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-profile]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-offline_access]
      signing_key: !Find
        - authentik_crypto.certificatekeypair
        - [name, authentik Self-signed Certificate]
  - model: authentik_core.application
    id: flux-application
    identifiers:
      slug: flux-web
    attrs:
      name: Flux
      provider: !KeyOf flux-provider
      meta_launch_url: https://flux.home.tom-mendy.com/
      meta_icon: https://flux.home.tom-mendy.com/favicon.svg
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf flux-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf flux-application
      group: !KeyOf flux-viewers
      order: 1
    attrs:
      enabled: true

  - model: authentik_providers_oauth2.oauth2provider
    id: coder-provider
    identifiers:
      name: Coder
    attrs:
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-authorization-implicit-consent]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      client_type: confidential
      client_id: coder
      client_secret: !Env [CODER_OIDC_CLIENT_SECRET, null]
      issuer_mode: per_provider
      grant_types:
        - authorization_code
        - refresh_token
      redirect_uris:
        - matching_mode: strict
          url: https://coder.home.tom-mendy.com/api/v2/users/oidc/callback
          redirect_uri_type: authorization
      property_mappings:
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-openid]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-email]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-profile]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-offline_access]
      signing_key: !Find
        - authentik_crypto.certificatekeypair
        - [name, authentik Self-signed Certificate]
  - model: authentik_core.application
    id: coder-application
    identifiers:
      slug: coder
    attrs:
      name: Coder
      provider: !KeyOf coder-provider
      meta_launch_url: https://coder.home.tom-mendy.com/
      meta_icon: https://coder.home.tom-mendy.com/favicon.ico
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf coder-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf coder-application
      group: !KeyOf coder-users
      order: 1
    attrs:
      enabled: true

  - model: authentik_providers_oauth2.oauth2provider
    id: matrix-provider
    identifiers:
      name: Matrix
    attrs:
      authorization_flow: !Find
        - authentik_flows.flow
        - [slug, default-authentication-flow]
      invalidation_flow: !Find
        - authentik_flows.flow
        - [slug, default-provider-invalidation-flow]
      client_type: confidential
      client_id: matrix
      client_secret: !Env [MATRIX_OIDC_CLIENT_SECRET, null]
      issuer_mode: per_provider
      grant_types:
        - authorization_code
        - refresh_token
      redirect_uris:
        - matching_mode: strict
          url: https://matrix.tom-mendy.com/_matrix/client/unstable/login/sso/callback/matrix
          redirect_uri_type: authorization
      property_mappings:
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-openid]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-email]
        - !Find
          - authentik_providers_oauth2.scopemapping
          - [managed, goauthentik.io/providers/oauth2/scope-profile]
      signing_key: !Find
        - authentik_crypto.certificatekeypair
        - [name, authentik Self-signed Certificate]
  - model: authentik_core.application
    id: matrix-application
    identifiers:
      slug: matrix
    attrs:
      name: Matrix
      provider: !KeyOf matrix-provider
      meta_launch_url: https://chat.tom-mendy.com/
      meta_icon: https://chat.tom-mendy.com/assets/favicon.ico
      policy_engine_mode: any
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf matrix-application
      group: !KeyOf homelab-admins
      order: 0
    attrs:
      enabled: true
  - model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf matrix-application
      group: !KeyOf matrix-users
      order: 1
    attrs:
      enabled: true
