rbac:
  create: true

alertmanager:
  enabled: false

server:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
    runAsNonRoot: false
  persistentVolume:
    enabled: true
    existingClaim: prometheus-server-pvc
  service:
    type: ClusterIP
