namespace: prometheus
createNamespace: true

storage:
  pvName: prometheus-server-pv
  pvcName: prometheus-server-pvc
  size: 50Gi
  nfsServer: 10.0.0.11
  nfsPath: /volume1/prometheus

ingress:
  name: prometheus-ingress
  host: prometheus.home.tom-mendy.com
  className: ""
  serviceName: prometheus-server
  servicePort: 80
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

rbac:
  create: true

scrapeConfigs:
  kubernetes-nodes-cadvisor:
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - source_labels:
          - __meta_kubernetes_node_name
        target_label: node
      - source_labels:
          - __metrics_path__
        target_label: metrics_path

alertmanager:
  enabled: false

server:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
    runAsNonRoot: false
  persistentVolume:
    enabled: true
    existingClaim: prometheus-server-pvc
  service:
    type: ClusterIP
