namespace: prometheus
createNamespace: true

storage:
  pvName: prometheus-server-pv
  pvcName: prometheus-server-pvc
  size: 50Gi
  nfsServer: 10.0.0.11
  nfsPath: /volume1/prometheus

ingress:
  name: prometheus-ingress
  host: prometheus.home.tom-mendy.com
  className: ""
  serviceName: prometheus-server
  servicePort: 80
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
