namespace: wakapi
createNamespace: true

replicaCount: 1

image:
  repository: ghcr.io/muety/wakapi
  tag: 2.18.0@sha256:9ee43d15009730928ed4c3506bdfb410522d9e6543d364d8c063e1e02348ba78
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: wakapi.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

dataStorage:
  pvcName: wakapi-data-pvc
  size: 5Gi
  storageClassName: nfs-k8s
