namespace: wakapi
createNamespace: true

replicaCount: 1

image:
  repository: ghcr.io/muety/wakapi
  tag: 2.17.4@sha256:6fce764acf8775e1166e8b03e59fb6b34744e4a9fba5e98d9ea15d341db31bf8
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: wakapi.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

dataStorage:
  pvcName: wakapi-data-pvc
  size: 5Gi
  storageClassName: nfs-k8s
