service:
  type: LoadBalancer

env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: traefik-cloudflare-dns
        key: CF_DNS_API_TOKEN

deployment:
  replicas: 1
  annotations:
    keel.sh/policy: minor

additionalArguments:
  - --entrypoints.web.http.redirections.entryPoint.to=:443
  - --entrypoints.web.http.redirections.entryPoint.scheme=https
  - --entrypoints.web.http.redirections.entryPoint.permanent=true
  - --certificatesresolvers.letsencrypt.acme.email=admin@tom-mendy.com
  - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
  - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
  - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=20

persistence:
  enabled: true
  name: traefik-data
  accessMode: ReadWriteOnce
  storageClass: nfs-k8s
  size: 128Mi
  path: /data

updateStrategy:
  type: Recreate

ports:
  web:
    expose:
      default: true
    exposedPort: 80
  websecure:
    expose:
      default: true
    exposedPort: 443
  forgejo-ssh:
    port: 2222
    expose:
      default: true
    exposedPort: 22
    protocol: TCP
