service:
  type: LoadBalancer

deployment:
  podAnnotations:
    keel.sh/policy: minor

ports:
  web:
    expose:
      default: true
    exposedPort: 80
  websecure:
    expose:
      default: true
    exposedPort: 443
