# openwebui-values.yaml
ollama:
  enabled: true
  host: ollama.ollama.svc.cluster.local
  port: 11434

podAnnotations:
  keel.sh/policy: all

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClass: "local-path"
  size: 50Gi
pipelines:
  enabled: false
  persistence:
    storageClass: local-path
    size: 50Gi