# openwebui-values.yaml
ollama:
  enabled: false # Don't install Ollama inside WebUI
  host: ollama.ollama.svc.cluster.local
  port: 11434

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  storageClass: "local-path"
  size: 50Gi
pipelines:
  persistence:
    storageClass: local-path
    size: 50Gi