namespace: openwebui

ingress:
  name: openwebui-ingress
  host: openwebui.home.tom-mendy.com
  className: ""
  serviceName: open-webui
  servicePort: 8080
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
