apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: {{ .Values.namespace }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INSTANCE_NAME
              value: {{ .Values.env.instanceName | quote }}
            - name: BASE_URL
              value: {{ .Values.env.baseUrl | quote }}
            - name: AUTOCOMPLETE
              value: {{ .Values.env.autocomplete | quote }}
            - name: SEARXNG_SERVER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: server-secret-key
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 30
            periodSeconds: 10
