namespace: newt-system

secret:
  name: newt-creds

infisicalSecret:
  enabled: true
  name: newt-creds
  serviceAccountName: newt-infisical-sync
  connectionName: newt-infisical
  authName: newt-infisical
  identitySecretName: newt-infisical-identity
  address: https://infisical.home.tom-mendy.com
  identityID: "78e81396-214b-4ae1-9b8e-438fc2c31dee"
  projectId: "758123bc-7eaa-4256-98a2-bb7438a783b8"
  envSlug: prod
  secretsPath: /newt

global:
  image:
    tag: 1.18.0@sha256:07507a530f3f239bee4dc208aabdd25095df650f132e926245659e1a67aa5de9

newtInstances:
  - name: main-tunnel
    enabled: true
    auth:
      existingSecretName: newt-creds
      keys:
        endpointKey: PANGOLIN_ENDPOINT
        idKey: NEWT_ID
        secretKey: NEWT_SECRET
