namespace: job-search-manager
image:
  repository: harbor.home.tom-mendy.com/job-search-manager/job-search-manager # {"$imagepolicy": "flux-system:job-search-manager:name"}
  tag: latest # {"$imagepolicy": "flux-system:job-search-manager:tag"}
  digest: sha256:2e1abb8f764eea310790f97e8143ca09ca1a7e625efe0763b60d86767b61eeb9 # {"$imagepolicy": "flux-system:job-search-manager:digest"}
  pullPolicy: Always
  pullSecret: job-search-manager-registry
ingress:
  host: suivi-stage.home.tom-mendy.com
database:
  image: ghcr.io/cloudnative-pg/postgresql:18.6-system-bullseye@sha256:899d3ed526b659d77935dde0e6bf2d69dbbf17d3d8c6486ca8cfd04bd3c18533
  storage: 5Gi
  storageClass: nfs-k8s
garage:
  image: dxflrs/garage:v2.4.1@sha256:9c96caa2612d3411acc5b0e6701fb238dbfba33e533a6d7d3d811a4b12d0d020
  storage: 20Gi
  storageClass: nfs-k8s
  bucket: job-search-documents
backup:
  image: public.ecr.aws/aws-cli/aws-cli:2.37.9@sha256:92de75724b6a746951f0e8b915d86bbccd7cb55aff96cd0cb4f7017272160780
runtimeSecret: job-search-manager-runtime
