namespace: job-search-manager
image:
  repository: harbor.home.tom-mendy.com/job-search-manager/job-search-manager # {"$imagepolicy": "flux-system:job-search-manager:name"}
  tag: latest # {"$imagepolicy": "flux-system:job-search-manager:tag"}
  digest: sha256:2e1abb8f764eea310790f97e8143ca09ca1a7e625efe0763b60d86767b61eeb9 # {"$imagepolicy": "flux-system:job-search-manager:digest"}
  pullPolicy: Always
  pullSecret: job-search-manager-registry
ingress:
  host: suivi-stage.home.tom-mendy.com
database:
  image: ghcr.io/cloudnative-pg/postgresql:18.4-system-bullseye@sha256:7af186660aead1b948d827ef1c52c20a8d2cb7b2a4089424b8f612e0a61dc2f9
  storage: 5Gi
  storageClass: nfs-k8s
garage:
  image: dxflrs/garage:v2.4.1@sha256:9c96caa2612d3411acc5b0e6701fb238dbfba33e533a6d7d3d811a4b12d0d020
  storage: 20Gi
  storageClass: nfs-k8s
  bucket: job-search-documents
backup:
  image: public.ecr.aws/aws-cli/aws-cli:2.37.6@sha256:82905aa8fdab6e2403b40dceec12dc33aea2535a4c2a6f13d596d98501951105
runtimeSecret: job-search-manager-runtime
