namespace: job-search-manager
image:
  repository: harbor.home.tom-mendy.com/job-search-manager/job-search-manager # {"$imagepolicy": "flux-system:job-search-manager:name"}
  tag: latest # {"$imagepolicy": "flux-system:job-search-manager:tag"}
  digest: sha256:a819ad39e731c3a2e78cb8163a553fc3e939bb214f85fbce3c4b64d7084e2703 # {"$imagepolicy": "flux-system:job-search-manager:digest"}
  pullPolicy: Always
  pullSecret: job-search-manager-registry
ingress:
  host: suivi-stage.home.tom-mendy.com
database:
  image: ghcr.io/cloudnative-pg/postgresql:17
  storage: 5Gi
  storageClass: nfs-k8s
garage:
  image: dxflrs/garage:v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
  storage: 20Gi
  storageClass: nfs-k8s
  bucket: job-search-documents
backup:
  image: public.ecr.aws/aws-cli/aws-cli:2.27.41
runtimeSecret: job-search-manager-runtime
