namespace: forgejo-runner
createNamespace: true

replicaCount: 1

forgejo:
  url: http://forgejo.forgejo.svc.cluster.local:3000/

runner:
  name: forgejo-runner-homelab
  image:
    repository: data.forgejo.org/forgejo/runner
    tag: 12.13.2@sha256:eb6e7bc21973382d261e6eb883dbd27b8cb56939d33a3bfd79a1352b7f9a33a0
    pullPolicy: IfNotPresent
  secretName: forgejo-runner-homelab
  logLevel: info
  capacity: 1
  timeout: 3h
  labels:
    - debian:docker://docker.io/library/node:lts
    - ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

docker:
  host: tcp://127.0.0.1:2375
  jobHost: tcp://dind.docker.internal:2375
  containerOptions: --add-host=dind.docker.internal:host-gateway
  image:
    repository: docker
    tag: dind@sha256:12e683a161823b2a839aeea999b9d960e6e1f9a97b1679ad6b441982e2d9cf07
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "2Gi"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

registryAuth:
  enabled: false
  secretName: forgejo-runner-harbor-ci
  usernameKey: HARBOR_CI_USERNAME
  tokenKey: HARBOR_CI_TOKEN

infisicalSecret:
  enabled: false
