apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  storageClassName: {{ .Values.postgres.storage.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin-config
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.atuin.storage.size }}
  storageClassName: {{ .Values.atuin.storage.storageClassName }}