apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.storage.pvcName | default "postgres-data" }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.postgres.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  storageClassName: {{ .Values.postgres.storage.storageClassName | quote }}
{{- if .Values.postgres.storage.pvName }}
  volumeName: {{ .Values.postgres.storage.pvName }}
{{- end }}
{{- if and .Values.postgres.storage.pvName .Values.postgres.storage.nfsServer .Values.postgres.storage.nfsPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.storage.pvName }}
spec:
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  accessModes:
    - {{ .Values.postgres.storage.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.postgres.storage.reclaimPolicy }}
  storageClassName: {{ .Values.postgres.storage.storageClassName | quote }}
  nfs:
    server: {{ .Values.postgres.storage.nfsServer }}
    path: {{ .Values.postgres.storage.nfsPath }}
{{- end }}
{{- if and .Values.atuin.storage.pvName .Values.atuin.storage.nfsServer .Values.atuin.storage.nfsPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.atuin.storage.pvName }}
spec:
  capacity:
    storage: {{ .Values.atuin.storage.size }}
  accessModes:
    - {{ .Values.atuin.storage.accessMode }}
  persistentVolumeReclaimPolicy: {{ .Values.atuin.storage.reclaimPolicy }}
  storageClassName: {{ .Values.atuin.storage.storageClassName | quote }}
  nfs:
    server: {{ .Values.atuin.storage.nfsServer }}
    path: {{ .Values.atuin.storage.nfsPath }}
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.atuin.storage.pvcName | default "atuin-config" }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.atuin.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.atuin.storage.size }}
  storageClassName: {{ .Values.atuin.storage.storageClassName | quote }}
{{- if .Values.atuin.storage.pvName }}
  volumeName: {{ .Values.atuin.storage.pvName }}
{{- end }}
