{{- if not .Values.infisicalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: atuin-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  ATUIN_DB_USERNAME: {{ .Values.atuin.db.user | quote }}
  ATUIN_DB_PASSWORD: {{ .Values.atuin.db.password | quote }}
  ATUIN_DB_URI: {{ printf "postgres://%s:%s@postgres/%s" .Values.atuin.db.user .Values.atuin.db.password .Values.atuin.db.name | quote }}
{{- end }}
