apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: {{ .Values.namespace }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: blocky
  ports:
    - name: dns
      protocol: UDP
      port: {{ .Values.service.dnsPort }}
      targetPort: {{ .Values.service.dnsPort }}
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
