{{- if and .Values.secret.create (not .Values.infisicalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  CF_DNS_API_TOKEN: {{ .Values.secret.apiToken | quote }}
{{- end }}
