apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://charts.keel.sh
      chart: keel
      targetRevision: "1.2.0"
      helm:
        releaseName: keel
        valueFiles:
          - $values/kubernetes/keel/keel-values.yaml
    - repoURL: ssh://git@forgejo.forgejo.svc.cluster.local/Tom-Mendy/homelab.git
      targetRevision: main
      ref: values
    - repoURL: ssh://git@forgejo.forgejo.svc.cluster.local/Tom-Mendy/homelab.git
      targetRevision: main
      path: kubernetes/keel
  destination:
    server: https://kubernetes.default.svc
    namespace: keel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
