{{- if .Values.infisicalSecret.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.infisicalSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  hostAPI: {{ .Values.infisicalSecret.hostAPI | quote }}
  syncConfig:
    resyncInterval: 1m
    instantUpdates: false
  authentication:
    kubernetesAuth:
      identityId: {{ .Values.infisicalSecret.identityID | quote }}
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: authentik-infisical-sync
        namespace: {{ .Values.namespace }}
      secretsScope:
        projectSlug: {{ .Values.infisicalSecret.projectSlug | quote }}
        envSlug: {{ .Values.infisicalSecret.envSlug | quote }}
        secretsPath: {{ .Values.infisicalSecret.secretsPath | quote }}
        recursive: false
  managedKubeSecretReferences:
    - secretName: {{ .Values.infisicalSecret.name }}
      secretNamespace: {{ .Values.namespace }}
      creationPolicy: Orphan
      template:
        includeAllSecrets: true
{{- end }}
