apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.oidc.blueprintConfigMapName }}
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/resource-policy: keep
data:
{{- range $path, $_ := .Files.Glob "blueprints/*.yaml" }}
  {{ base $path }}: |
{{ $.Files.Get $path | nindent 4 }}
{{- end }}
