{{- range $outpost := .Values.outpostIngresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $outpost.name }}-authentik-outpost
  namespace: {{ $.Values.namespace }}
  annotations:
{{ include "authentik-local.outpostAnnotations" $ | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ $outpost.host }}
  rules:
    - host: {{ $outpost.host }}
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: {{ include "authentik-local.serverServiceName" $ }}
                port:
                  number: 80
{{ end }}
