- name: Add Argo Helm repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Deploy Argo CD via Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    values: "{{ lookup('file', playbook_dir + '/../../kubernetes/argocd/argocd-values.yaml') | from_yaml }}"

- name: Apply Argo CD Ingress
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', playbook_dir + '/../../kubernetes/argocd/argocd-ingress.yaml') | from_yaml }}"
