- name: Load Forgejo manifest
  ansible.builtin.set_fact:
    forgejo_definitions: "{{ lookup('file', playbook_dir + '/../../kubernetes/forgejo/forgejo.yaml') | from_yaml_all }}"

- name: Deploy Forgejo
  kubernetes.core.k8s:
    state: present
    definition: "{{ forgejo_definitions }}"
