- name: Add Grafana Helm repo
  kubernetes.core.helm_repository:
    name: grafana-community
    repo_url: https://grafana-community.github.io/helm-charts

- name: Deploy Grafana local Helm chart (admin secret)
  kubernetes.core.helm:
    name: grafana-local-extras
    chart_ref: "{{ playbook_dir + '/../../kubernetes/grafana' }}"
    release_namespace: grafana
    create_namespace: true

- name: Deploy Grafana via Helm
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana-community/grafana
    release_namespace: grafana
    create_namespace: true
    values: "{{ lookup('file', playbook_dir + '/../../kubernetes/grafana/grafana-values.yaml') | from_yaml }}"
