- name: Add Keel Helm repo
  kubernetes.core.helm_repository:
    name: keel
    repo_url: https://charts.keel.sh
  register: keel_repo_add
  failed_when: keel_repo_add.failed and ('already have a repository named keel' not in (keel_repo_add.msg | default('') | lower))

- name: Deploy Keel via Helm
  kubernetes.core.helm:
    name: keel
    chart_ref: keel/keel
    release_namespace: keel
    create_namespace: true
    values: "{{ lookup('file', playbook_dir + '/../../kubernetes/keel/keel-values.yaml') | from_yaml }}"

- name: Deploy Keel local Helm chart (ingress)
  kubernetes.core.helm:
    name: keel-local-extras
    chart_ref: "{{ playbook_dir + '/../../kubernetes/keel' }}"
    release_namespace: keel
    create_namespace: true
