- name: Add Traefik Helm repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts

- name: Deploy Traefik local Helm chart (Cloudflare secret)
  kubernetes.core.helm:
    name: traefik-local-extras
    chart_ref: "{{ playbook_dir + '/../../kubernetes/traefik' }}"
    release_namespace: traefik
    create_namespace: true

- name: Deploy Traefik Ingress Controller
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    create_namespace: true
    values: "{{ lookup('file', playbook_dir + '/../../kubernetes/traefik/traefik-values.yaml') | from_yaml }}"
