apiVersion: v1
kind: Service
metadata:
  name: tuwunel
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: tuwunel
  ports:
    - name: http
      port: 8008
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: cinny
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: cinny
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-rtc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: matrix-rtc
  ports:
    - name: websocket
      port: 7880
      targetPort: websocket
    - name: rtc-tcp
      port: 7881
      targetPort: rtc-tcp
    {{- range $port := untilStep 50100 50111 1 }}
    - name: udp-{{ $port }}
      port: {{ $port }}
      targetPort: udp-{{ $port }}
      protocol: UDP
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: matrix-rtc-jwt
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: matrix-rtc
  ports:
    - name: jwt
      port: 8081
      targetPort: jwt
