apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-k8s
  volumeName: pvc-090fcf5b-66f0-457f-9279-f5167b075af5
