---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/
# icons found here https://github.com/homarr-labs/dashboard-icons

- Homelab:
    - Prometheus:
        icon: prometheus.svg
        href: https://prometheus.home.tom-mendy.com
        description: Metrics and monitoring
    - Grafana:
        icon: grafana.svg
        href: https://grafana.home.tom-mendy.com
        description: Dashboards
    - NAS Synology:
        icon: synology.svg
        href: https://192.168.1.1:5001/
        description: NAS

- Professional Tools:
    - OpenWebUI:
        href: https://openwebui.home.tom-mendy.com/
        description: Chat UI for local LLMs
    - SearXNG:
        icon: searxng.svg
        href: https://searxng.home.tom-mendy.com/
        description: Privacy-respecting metasearch engine
    - Stirling PDF:
        icon: stirling-pdf.svg
        href: https://stirling-pdf.home.tom-mendy.com/
        description: Web Application to Edit PDF
    - Atuin:
        href: https://atuin.home.tom-mendy.com/
        description: Shell history sync and search
    - Vaultwarden:
        icon: vaultwarden.svg
        href: https://vaultwarden.home.tom-mendy.com/
        description: Password manager
    - qBittorrent:
        icon: qbittorrent.svg
        href: https://qbittorrent.home.tom-mendy.com/
        description: Torrent downloader (VPN)
    - NZBGet:
        icon: nzbget.svg
        href: https://nzbget.home.tom-mendy.com/
        description: Usenet downloader (VPN)

- Entertainment:
    - Navidrome:
        icon: navidrome.svg
        href: https://navidrome.home.tom-mendy.com/
        description: Music player

- Developer:
    - Argo CD:
        icon: argo-cd.svg
        href: https://argocd.home.tom-mendy.com/
        description: GitOps continuous delivery
    - Forgejo:
        icon: forgejo.svg
        href: https://forgejo.home.tom-mendy.com/
        description: Git forge

- Arr Apps:
    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.home.tom-mendy.com/
        description: Indexer manager
    - Sonarr:
        icon: sonarr.svg
        href: https://sonarr.home.tom-mendy.com/
        description: TV series manager
    - Radarr:
        icon: radarr.svg
        href: https://radarr.home.tom-mendy.com/
        description: Movies manager
    - Bazarr:
        icon: bazarr.svg
        href: https://bazarr.home.tom-mendy.com/
        description: Subtitle manager
    - Autobrr:
        icon: autobrr.svg
        href: https://autobrr.home.tom-mendy.com/
        description: Automation and racing