namespace: homepage

replicaCount: 1

image:
  repository: ghcr.io/gethomepage/homepage
  tag: v1.13.1@sha256:d8d784e5090111b6e4c56dfd90e272d2953a2094e87349f647165df0fa6c4401
  pullPolicy: IfNotPresent

allowedHosts: homepage.home.tom-mendy.com

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: homepage.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
