- name: Deploy Kubernetes Applications
  hosts: kube_control_plane
  tasks:
    - name: Ensure kubernetes and yaml python libraries are installed (APT)
      become: true
      ansible.builtin.apt:
        name:
          - python3-kubernetes
          - python3-yaml
        state: present
        update_cache: yes

    - name: Label node-3 for GPU
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: node-3
            labels:
              gpu: "true"

    - name: Deploy Blocky
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/../../kubernetes/blocky/blocky.yaml') | from_yaml_all }}"

    - name: Deploy Trilium
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/../../kubernetes/tritium.yml') | from_yaml_all }}"

    - name: Add Keel Helm repo
      kubernetes.core.helm_repository:
        name: keel
        repo_url: https://keel-hq.github.io/keel

    - name: Deploy Keel via Helm
      kubernetes.core.helm:
        name: keel
        chart_ref: keel/keel
        release_namespace: keel
        create_namespace: true
        values: "{{ lookup('file', playbook_dir + '/../../kubernetes/keel/keel-values.yaml') | from_yaml }}"

    - name: Apply Keel Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/../../kubernetes/keel/keel-ingress.yaml') | from_yaml }}"

    - name: Add Ollama Helm repo
      kubernetes.core.helm_repository:
        name: otwld
        repo_url: https://helm.otwld.com/

    - name: Deploy Ollama via Helm
      kubernetes.core.helm:
        name: ollama
        chart_ref: otwld/ollama
        release_namespace: ollama
        create_namespace: true
        values: "{{ lookup('file', playbook_dir + '/../../kubernetes/ollama/ollama-values.yaml') | from_yaml }}"

    - name: Apply Ollama Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/../../kubernetes/ollama/ollama-ingress.yaml') | from_yaml }}"

    - name: Add OpenWebUI Helm repo
      kubernetes.core.helm_repository:
        name: open-webui
        repo_url: https://helm.openwebui.com/

    - name: Deploy Local Path Provisioner
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.32/deploy/local-path-storage.yaml

    - name: Deploy OpenWebUI via Helm
      kubernetes.core.helm:
        name: openwebui
        chart_ref: open-webui/open-webui
        release_namespace: openwebui
        create_namespace: true
        values: "{{ lookup('file', playbook_dir + '/../../kubernetes/openwebui/openwebui-values.yaml') | from_yaml }}"

    - name: Apply OpenWebUI Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', playbook_dir + '/../../kubernetes/openwebui/openwebui-ingress.yaml') | from_yaml }}"
