namespace: agent

image:
  repository: ghcr.io/vectorize-io/hindsight-api
  digest: sha256:1ba631f950a04460feff6b1e212bad3cdf127b0cfb3d765bdcba12f512481d7b
  pullPolicy: IfNotPresent

service:
  port: 8888

controlPlane:
  image:
    repository: ghcr.io/vectorize-io/hindsight-control-plane
    tag: 0.10.2@sha256:f6e3802e558a0c57feff84d52dfc276d0a841bc21de114629a90444eadc5a3f3
    pullPolicy: IfNotPresent
  service:
    port: 9999
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  host: hindsight.home.tom-mendy.com
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: agent-authentik-hindsight@kubernetescrd

persistence:
  storageClass: nfs-k8s
  size: 10Gi

ollama:
  url: http://ollama.ollama.svc.cluster.local:11434/v1
  model: gemma4:e4b
  timeout: 600

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 6Gi
