runner:
  name: forgejo-runner-buildkit
  secretName: forgejo-runner-buildkit
  labels:
    - buildkit:docker://harbor.home.tom-mendy.com/homelab/ci/buildkit-forgejo@sha256:3431ed482ff11bcaae957fc5cc257aff09f62bea4758a319e2a82155d27e5017
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "4Gi"

docker:
  containerOptions: >-
    --add-host=dind.docker.internal:host-gateway
    --security-opt seccomp=unconfined
    --security-opt apparmor=unconfined
    --security-opt systempaths=unconfined

registryAuth:
  enabled: false

infisicalSecret:
  enabled: false
