runner:
  name: forgejo-runner-buildkit
  secretName: forgejo-runner-buildkit
  labels:
    - buildkit:docker://harbor.home.tom-mendy.com/homelab/ci/buildkit-forgejo@sha256:573c108b9221ef005ba2d62885f64b0028147ce5dbfc0b267843530ab286b26f
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "4Gi"

docker:
  containerOptions: >-
    --add-host=dind.docker.internal:host-gateway
    --device=/dev/fuse
    --security-opt seccomp=unconfined
    --security-opt apparmor=unconfined
    --security-opt systempaths=unconfined
  dataSizeLimit: 80Gi
  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
      ephemeral-storage: "20Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
      ephemeral-storage: "80Gi"

registryAuth:
  enabled: false

infisicalSecret:
  enabled: false
