deploymentSize: small
publicAddr: kasm.home.tom-mendy.com

proxyService:
  type: ClusterIP

ingress:
  enabled: true
  tls: true
  backendProtocol: http
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
