apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  admin-user: {{ .Values.secret.adminUser | quote }}
  admin-password: {{ .Values.secret.adminPassword | quote }}
