namespace: navidrome
createNamespace: true

replicaCount: 1

image:
  repository: deluan/navidrome
  tag: 0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2
  pullPolicy: IfNotPresent

deploymentAnnotations:
  keel.sh/policy: all

service:
  type: ClusterIP
  port: 4533

ingress:
  enabled: true
  host: navidrome.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

musicStorage:
  pvName: navidrome-music-pv
  pvcName: navidrome-music-pvc
  size: 200Gi
  nfsServer: 10.0.0.11
  nfsPath: /volume1/music

dataStorage:
  pvcName: navidrome-data-pvc
  size: 5Gi
  storageClassName: nfs-k8s
