namespace: authentik

cluster:
  name: authentik-postgres
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 10Gi
    storageClass: nfs-k8s
  database: authentik
  owner: authentik
  ownerSecret: authentik-postgres-app

