namespace: matrix

deploymentAnnotations:
  secrets.infisical.com/auto-reload: "true"

infisicalSecret:
  serviceAccountName: matrix-infisical-sync
  connectionName: matrix-infisical
  authName: matrix-infisical
  identitySecretName: matrix-infisical-identity
  address: https://infisical.home.tom-mendy.com
  identityID: "b8b289b4-f869-4547-94e1-ce89928ce5a9"
  projectId: "758123bc-7eaa-4256-98a2-bb7438a783b8"
  envSlug: prod
  secretsPath: /matrix

tuwunel:
  image: ghcr.io/matrix-construct/tuwunel:v1.8.3@sha256:699fa9971c174e01c884abad8d1a3cfb2fe518e1a71f1fa16ea9dedf11873d74
  host: matrix.tom-mendy.com
  storage:
    dataSize: 50Gi
    backupSize: 20Gi
    storageClass: nfs-k8s
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

cinny:
  image: ghcr.io/cinnyapp/cinny:v4.12.6@sha256:a7805a8a60ff621d343c128dbca6ba42ac5383ed5292522fd72248a77b9c836f
  host: chat.tom-mendy.com
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

rtc:
  host: rtc.tom-mendy.com
  publicIp: 92.222.90.223
  livekitImage: livekit/livekit-server:v1.13.5@sha256:3497163e15c48fef6e7830c78716f9e9d5edc28abf7aa90b61c86e93bbc306b1
  jwtImage: ghcr.io/element-hq/lk-jwt-service:0.5.0@sha256:29918567e6b7cd920e2853b4cd6848ce01b79947c3d19a9f1ed5b74f0a2a88bf
  resources:
    livekit:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: "1"
        memory: 1Gi
    jwt:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
