namespace: grafana

service:
  type: ClusterIP

deploymentStrategy:
  type: Recreate

initChownData:
  enabled: false

persistence:
  enabled: true
  storageClassName: nfs-k8s
  accessModes:
    - ReadWriteOnce
  size: 5Gi

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  hosts:
    - grafana.home.tom-mendy.com
  path: /
  pathType: Prefix
  tls:
    - hosts:
        - grafana.home.tom-mendy.com

envValueFrom:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
    secretKeyRef:
      name: grafana-oidc
      key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET

grafana.ini:
  server:
    root_url: https://grafana.home.tom-mendy.com
  auth.generic_oauth:
    enabled: true
    name: Authentik
    allow_sign_up: true
    client_id: grafana
    client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
    scopes: openid profile email offline_access
    auth_url: https://authentik.home.tom-mendy.com/application/o/authorize/
    token_url: https://authentik.home.tom-mendy.com/application/o/token/
    api_url: https://authentik.home.tom-mendy.com/application/o/userinfo/
    role_attribute_path: >-
      contains(groups[*], 'homelab-admins') && 'Admin' || 'Viewer'
    role_attribute_strict: true
    use_pkce: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.prometheus.svc.cluster.local
        isDefault: true
        editable: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboardsConfigMaps:
  default: grafana-dashboards
