namespace: stirling-pdf

replicaCount: 1

image:
  repository: stirlingtools/stirling-pdf
  tag: latest@sha256:950c596db26e0764f642def2fd4f9ee904ff2ac16d83fe621ff731b771d9b385
  pullPolicy: IfNotPresent

deploymentAnnotations:
  keel.sh/policy: all

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: stirling-pdf.home.tom-mendy.com
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
