namespace: atuin

replicaCount: 1

nfsPermissions:
  userUid: "1025"
  userGid: "100"

atuin:
  image:
    repository: ghcr.io/atuinsh/atuin
    tag: 18.20.1@sha256:ff9a5c426bb6df99adbc09505182d5aed1524d123f973c40b18de56d25c3562a
    pullPolicy: IfNotPresent
  host: atuin.home.tom-mendy.com
  port: 8888
  openRegistration: false
  db:
    name: atuin
    user: ""
    password: ""
  storage:
    pvName: ""
    pvcName: atuin-config-v2
    size: 20Gi
    accessMode: ReadWriteMany
    reclaimPolicy: Retain
    storageClassName: nfs-k8s
    nfsServer: ""
    nfsPath: ""

postgres:
  image:
    repository: postgres
    tag: 16.15@sha256:f1c3376c26f2609ab9f29f71f824103fe2fcd8ee0346485cb6122a4f93df6f94
    pullPolicy: IfNotPresent
  port: 5432
  storage:
    pvName: ""
    pvcName: postgres-data-v2
    size: 10Gi
    accessMode: ReadWriteOnce
    reclaimPolicy: Retain
    storageClassName: nfs-k8s
    nfsServer: ""
    nfsPath: ""

service:
  type: ClusterIP

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

infisicalSecret:
  enabled: true
  name: atuin-secrets
  serviceAccountName: atuin-infisical-sync
  connectionName: atuin-infisical
  authName: atuin-infisical
  identitySecretName: atuin-infisical-identity
  address: https://infisical.home.tom-mendy.com
  identityID: "7b4de8a4-b92f-4694-8183-4b026262442f"
  projectId: "758123bc-7eaa-4256-98a2-bb7438a783b8"
  envSlug: prod
  secretsPath: /atuin
