namespace: atuin

replicaCount: 1

nfsPermissions:
  userUid: "1025"
  userGid: "100"

atuin:
  image:
    repository: ghcr.io/atuinsh/atuin
    tag: latest@sha256:9a3bf220acd36873004fe18a9abb2bcd2d74a8c3522e52d309ba7c53d971c01f
    pullPolicy: IfNotPresent
  host: atuin.home.tom-mendy.com
  port: 8888
  openRegistration: false
  db:
    name: atuin
    user: ""
    password: ""
  storage:
    pvName: ""
    pvcName: atuin-config-v2
    size: 20Gi
    accessMode: ReadWriteMany
    reclaimPolicy: Retain
    storageClassName: nfs-k8s
    nfsServer: ""
    nfsPath: ""

postgres:
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  port: 5432
  storage:
    pvName: ""
    pvcName: postgres-data-v2
    size: 10Gi
    accessMode: ReadWriteOnce
    reclaimPolicy: Retain
    storageClassName: nfs-k8s
    nfsServer: ""
    nfsPath: ""

deploymentAnnotations:
  keel.sh/policy: all

service:
  type: ClusterIP

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

infisicalSecret:
  enabled: true
  name: atuin-secrets
  serviceAccountName: atuin-infisical-sync
  connectionName: atuin-infisical
  authName: atuin-infisical
  identitySecretName: atuin-infisical-identity
  address: https://infisical.home.tom-mendy.com
  identityID: "7b4de8a4-b92f-4694-8183-4b026262442f"
  projectId: "758123bc-7eaa-4256-98a2-bb7438a783b8"
  envSlug: prod
  secretsPath: /atuin
