apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: {{ .Values.namespace }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
        - name: forgejo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
              name: http
            - containerPort: {{ .Values.service.sshPort }}
              name: ssh
          env:
            - name: USER_UID
              value: {{ .Values.user.uid | quote }}
            - name: USER_GID
              value: {{ .Values.user.gid | quote }}
            - name: FORGEJO__server__ROOT_URL
              value: {{ .Values.rootUrl | quote }}
            - name: FORGEJO__oauth2_client__ENABLE_AUTO_REGISTRATION
              value: {{ .Values.oauth2Client.enableAutoRegistration | quote }}
            - name: FORGEJO__oauth2_client__USERNAME
              value: {{ .Values.oauth2Client.username | quote }}
            - name: FORGEJO__actions__ENABLED
              value: {{ .Values.actions.enabled | quote }}
            - name: FORGEJO__actions__DEFAULT_ACTIONS_URL
              value: {{ .Values.actions.defaultActionsUrl | quote }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.storage.pvcName }}
