apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: forgejo
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: {{ .Values.service.sshPort }}
