---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder-extras
spec:
  interval: 30m
  timeout: 10m
  releaseName: coder-extras
  targetNamespace: coder
  storageNamespace: coder
  chart:
    spec:
      chart: ./kubernetes/coder
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: authentik-extras
    - name: cloudnative-pg
    - name: nfs-provisioner
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 30m
  timeout: 15m
  releaseName: coder
  targetNamespace: coder
  storageNamespace: coder
  chart:
    spec:
      chart: coder
      version: 2.35.3
      sourceRef:
        kind: HelmRepository
        name: coder
  valuesFrom:
    - kind: ConfigMap
      name: coder-values
  dependsOn:
    - name: coder-extras
    - name: traefik
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 30m
  timeout: 10m
  releaseName: grafana
  targetNamespace: grafana
  storageNamespace: grafana
  chart:
    spec:
      chart: grafana
      version: 12.4.1
      sourceRef:
        kind: HelmRepository
        name: grafana
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
  dependsOn:
    - name: grafana-extras
    - name: authentik-extras
    - name: nfs-provisioner
    - name: prometheus
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-extras
spec:
  interval: 30m
  timeout: 10m
  releaseName: grafana-extras
  targetNamespace: grafana
  storageNamespace: grafana
  chart:
    spec:
      chart: ./kubernetes/grafana
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
spec:
  interval: 30m
  timeout: 10m
  releaseName: navidrome
  targetNamespace: navidrome
  storageNamespace: navidrome
  chart:
    spec:
      chart: ./kubernetes/navidrome
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: nfs-provisioner
    - name: searxng
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 30m
  timeout: 10m
  releaseName: vaultwarden
  targetNamespace: vaultwarden
  storageNamespace: vaultwarden
  chart:
    spec:
      chart: ./kubernetes/vaultwarden
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: nfs-provisioner
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trilium
spec:
  interval: 30m
  timeout: 10m
  releaseName: trilium
  targetNamespace: default
  storageNamespace: default
  chart:
    spec:
      chart: ./kubernetes/trilium
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: traefik
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atuin
spec:
  interval: 30m
  timeout: 10m
  releaseName: atuin
  targetNamespace: atuin
  storageNamespace: atuin
  chart:
    spec:
      chart: ./kubernetes/atuin
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: authentik
    - name: infisical
    - name: infisical-operator
    - name: nfs-provisioner
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: endfield
spec:
  interval: 30m
  timeout: 10m
  releaseName: endfield
  targetNamespace: endfield
  storageNamespace: endfield
  chart:
    spec:
      chart: ./kubernetes/endfield
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: infisical
    - name: infisical-operator
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 30m
  timeout: 10m
  releaseName: forgejo
  targetNamespace: forgejo
  storageNamespace: forgejo
  chart:
    spec:
      chart: ./kubernetes/forgejo
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: authentik-extras
    - name: nfs-provisioner
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: media
spec:
  interval: 30m
  timeout: 15m
  releaseName: media
  targetNamespace: media
  storageNamespace: media
  chart:
    spec:
      chart: ./kubernetes/media
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: infisical
    - name: infisical-operator
    - name: nfs-provisioner
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix
spec:
  interval: 30m
  timeout: 15m
  releaseName: matrix
  targetNamespace: matrix
  storageNamespace: matrix
  chart:
    spec:
      chart: ./kubernetes/matrix
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: authentik-extras
    - name: infisical-operator
    - name: nfs-provisioner
    - name: traefik
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
spec:
  interval: 30m
  timeout: 10m
  releaseName: newt
  targetNamespace: newt-system
  storageNamespace: newt-system
  chart:
    spec:
      chart: newt
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: newt
  valuesFrom:
    - kind: ConfigMap
      name: newt-values
  dependsOn:
    - name: traefik
  install:
    createNamespace: true
    disableSchemaValidation: true
  upgrade:
    disableSchemaValidation: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt-extras
spec:
  interval: 30m
  timeout: 10m
  releaseName: newt-extras
  targetNamespace: newt-system
  storageNamespace: newt-system
  chart:
    spec:
      chart: ./kubernetes/newt
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: infisical
    - name: infisical-operator
    - name: newt
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
spec:
  interval: 30m
  timeout: 10m
  releaseName: ollama
  targetNamespace: ollama
  storageNamespace: ollama
  chart:
    spec:
      chart: ./kubernetes/ollama
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: authentik
    - name: cloudnative-pg
    - name: nfs-provisioner
    - name: searxng
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
spec:
  interval: 30m
  timeout: 10m
  releaseName: stirling-pdf
  targetNamespace: stirling-pdf
  storageNamespace: stirling-pdf
  chart:
    spec:
      chart: ./kubernetes/stirling-pdf
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: nfs-provisioner
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
spec:
  interval: 30m
  timeout: 10m
  releaseName: blocky
  targetNamespace: blocky
  storageNamespace: blocky
  chart:
    spec:
      chart: ./kubernetes/blocky
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  timeout: 10m
  releaseName: homepage
  targetNamespace: homepage
  storageNamespace: homepage
  chart:
    spec:
      chart: ./kubernetes/homepage
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keel
spec:
  interval: 30m
  timeout: 10m
  releaseName: keel
  targetNamespace: keel
  storageNamespace: keel
  chart:
    spec:
      chart: keel
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: keel
  valuesFrom:
    - kind: ConfigMap
      name: keel-values
  dependsOn:
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keel-extras
spec:
  interval: 30m
  timeout: 10m
  releaseName: keel-extras
  targetNamespace: keel
  storageNamespace: keel
  chart:
    spec:
      chart: ./kubernetes/keel
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: infisical
    - name: infisical-operator
    - name: keel
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 30m
  timeout: 10m
  releaseName: prometheus
  targetNamespace: prometheus
  storageNamespace: prometheus
  chart:
    spec:
      chart: prometheus
      version: 29.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values
  dependsOn:
    - name: nfs-provisioner
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-extras
spec:
  interval: 30m
  timeout: 10m
  releaseName: prometheus-extras
  targetNamespace: prometheus
  storageNamespace: prometheus
  chart:
    spec:
      chart: ./kubernetes/prometheus
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: prometheus
  install:
    createNamespace: true
  driftDetection:
    mode: enabled

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: searxng
spec:
  interval: 30m
  timeout: 10m
  releaseName: searxng
  targetNamespace: searxng
  storageNamespace: searxng
  chart:
    spec:
      chart: ./kubernetes/searxng
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
  dependsOn:
    - name: infisical
    - name: infisical-operator
    - name: traefik
  install:
    createNamespace: true
  driftDetection:
    mode: enabled
