replicaCount: 2
image:
  repository: harbor.home.tom-mendy.com/portfolio/portfolio # {"$imagepolicy": "flux-system:portfolio:name"}
  tag: latest # {"$imagepolicy": "flux-system:portfolio:tag"}
  digest: sha256:0abe97a78b3f9f47e2b2d3d06dd9ef2580dbc16dd2003436ead04c93a30561b0 # {"$imagepolicy": "flux-system:portfolio:digest"}
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: portfolio-registry-auth
service:
  port: 80
  targetPort: 8080
ingress:
  host: tom-mendy.com
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi
