replicaCount: 2

image:
  repository: harbor.home.tom-mendy.com/portfolio/portfolio # {"$imagepolicy": "flux-system:portfolio:name"}
  tag: latest # {"$imagepolicy": "flux-system:portfolio:tag"}
  digest: sha256:87d9fd9ee48f5ec84ad2b3042703ffe5d22ebc777be1b53b3132eb61a33a4277 # {"$imagepolicy": "flux-system:portfolio:digest"}
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: portfolio-registry-auth

service:
  port: 80
  targetPort: 8080

ingress:
  host: tom-mendy.com
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 100m
    memory: 64Mi
